### ISSUE TITLE
multi cdata  in content support

### ISSUE THREAD

**Issue by BiteBit** [rla/fast-feed#11]
hi, i'm have a problem
now fast-feed not support multi cdata content
like 
http://www.ruanyifeng.com/blog/atom.xml

**Comment by rla** [comment]
I think the behavior is as described here: http://stackoverflow.com/questions/21029167/rapidxml-giving-empty-cdata-nodes

I'm looking into detecting CDATA nodes under important nodes and extracting them. The content should be the text content of CDATA nodes concatenated?

**Comment by BiteBit** [comment]
yes,i think CDATA under the some node need to be concatenated

**Comment by rla** [comment]
Implemented it. This required custom allocation for concatenated string. Should have almost no performance penalty for code that has no multiple cdata elements. Also added small unit test and a memory leak test. Published new version 1.1.0. Reopen if more issues with it.

**Comment by BiteBit** [comment]
I had test the new version. Prefect!
Thank you.
