### ISSUE TITLE
Upgrade to NAN 2.x

### ISSUE THREAD

**Issue by rla** [rla/fast-feed#25]
This will require lots of changes. Example diff from another project:

https://github.com/danielkhan/node-gc-profiler/commit/25a2bbb950b483e63e97fc0bf7d39fbb04b8acee#diff-7b4f9baafdc929904b65af017eaa2da6

Required for Node/io 4.x support.

**Comment by ChALkeR** [comment]
Adding to the list: https://github.com/nodejs/node/issues/2798.

**Comment by rla** [comment]
This has been done in the commit:

https://github.com/rla/fast-feed/commit/e7e2d31d1b34405782a3af524c8fff2052f94328

New version 1.5.2 has been released.
